version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  csharpsampleapp:
    image: csharpsampleapp
    build:
      context: .
      dockerfile: src/csharp-sample-app.API/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mongo
    links:
      - mongo